FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./internal/services/api_gateway/cmd

FROM alpine:latest

WORKDIR /root/

ARG API_GATEWAY_CONFIG_PATH
ARG PORT
ARG HOST
ARG API_GATEWAY_SERVICES_CONFIG_PATH
ARG USER_SERVICE_URL
ARG NOTIFICATION_SERVICE_URL
ARG POST_SERVICE_URL

ENV HOST=${API_GATEWAY_HOST}
ENV PORT=${API_GATEWAY_PORT}
ENV API_GATEWAY_CONFIG_PATH=${API_GATEWAY_CONFIG_PATH}
ENV API_GATEWAY_SERVICES_CONFIG_PATH=${API_GATEWAY_SERVICES_CONFIG_PATH}
ENV USER_SERVICE_URL=${USER_SERVICE_URL}
ENV NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
ENV POST_SERVICE_URL=${POST_SERVICE_URL}

COPY --from=builder /app/gateway .
COPY --from=builder /app/internal/services/api_gateway/config ./config/

EXPOSE ${PORT}

CMD ["./gateway"]
